embed: switch back to text section after embedding
section was set to .rodata throughout the executable, causing linker
failures. adding ".text" in the inline assembler macro fixes this.

resolved error message:
Error: can't resolve `.rodata' {.rodata section} - `.Ltext0' {.text section}